from PyQt5 import QtCore, QtGui, QtWidgets
import math
import numpy as np
import matplotlib.pyplot as plt
class Ui_Form(object):
    islem=sayi1=sayi2=0
    def ekle(self,sayi):
        if (sayi=="0"):
            if (self.lineekran.text()!=0):
                self.lineekran.setText(self.lineekran.text()+"0")
        else:
            self.lineekran.setText(self.lineekran.text()+str(sayi))
    def temizle(self):
        self.lineekran.setText("")
    def hsp(self):
        self.sayi1=int(self.lineekran.text())      
        self.lineekran.setText("")    
    def topla(self):
        self.islem=1
        self.hsp()
    def cikarma(self):
        self.islem=2
        self.hsp()
    def carpma(self):
        self.islem=3
        self.hsp()
    def bolme(self):
        self.islem=4
        self.hsp()
    def sin(self):
        self.islem=5
        self.hsp()
    def cos(self):
        self.islem=6
        self.hsp()
    def tan(self):
        self.islem=7
        self.hsp()
    def kot(self):
        self.islem=8
        self.hsp()  
    def singrafik(self):
        self.sayitxt=(self.lineekran.text())
        if ':' in self.sayitxt:
            degerler=self.sayitxt.split(":")
            genlik=float(degerler[0])
            frekans=float(degerler[1])
            print(degerler)
            print(genlik)
            print(frekans)
            t=np.arange(0,1,0.001)
            y=np.sin(2*np.pi*frekans*t)*genlik
            plt.plot(t,y)
            plt.show()
    def cosgrafik(self):
        self.sayitxt=(self.lineekran.text())
        if ':' in self.sayitxt:
            degerler=self.sayitxt.split(":")
            genlik=float(degerler[0])
            frekans=float(degerler[1])
            print(degerler)
            print(genlik)
            print(frekans)
            t=np.arange(0,1,0.001)
            y=np.cos(2*np.pi*frekans*t)*genlik
            plt.plot(t,y)
            plt.show()
    def tangrafik(self):
        self.sayitxt=(self.lineekran.text())
        if ':' in self.sayitxt:
            degerler=self.sayitxt.split(":")
            genlik=float(degerler[0])
            frekans=float(degerler[1])
            print(degerler)
            print(genlik)
            print(frekans)
            t=np.arange(0,1,0.001)
            y=np.tan(2*np.pi*frekans*t)*genlik
            plt.plot(t,y)
            plt.show()
    def kotgrafik(self):
        self.sayitxt=(self.lineekran.text())
        if ':' in self.sayitxt:
            degerler=self.sayitxt.split(":")
            genlik=float(degerler[0])
            frekans=float(degerler[1])
            print(degerler)
            print(genlik)
            print(frekans)
            t=np.arange(0,1,0.001)
            y=np.arctan(2*np.pi*frekans*t)*genlik
            plt.plot(t,y)
            plt.show()
    
    def esittir(self):
        if (self.lineekran.text()!=""):
            self.sayitxt=(self.lineekran.text()).replace(",",".")
            self.sayi2=float(self.sayitxt)
            
            
            if (self.islem==1):
                self.lineekran.setText(str(self.sayi1+self.sayi2))
            if (self.islem==2):
                self.lineekran.setText(str(self.sayi1-self.sayi2))
            if (self.islem==3):
                self.lineekran.setText(str(self.sayi1*self.sayi2))
            if (self.islem==4):
                self.lineekran.setText(str(self.sayi1/self.sayi2))
            if (self.islem==5):
                self.lineekran.setText(str(math.sin(float(self.sayi2)*np.pi/180))) 
            if (self.islem==6):
                 self.lineekran.setText(str(math.cos(float(self.sayi2)*np.pi/180)))  
            if (self.islem==7):
                 self.lineekran.setText(str(math.tan(float(self.sayi2)*np.pi/180)))  
            if (self.islem==8):
                 self.lineekran.setText(str(math.atan(float(self.sayi2)*np.pi/180)))              
            self.islem=self.sayi1=self.sayi2=0
    
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 388)
        self.p4 = QtWidgets.QPushButton(Form)
        self.p4.setGeometry(QtCore.QRect(120, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p4.setFont(font)
        self.p4.setObjectName("p4")
        self.pcikis = QtWidgets.QPushButton(Form)
        self.pcikis.setGeometry(QtCore.QRect(70, 320, 75, 23))
        self.pcikis.setObjectName("pcikis")
        self.psinus = QtWidgets.QPushButton(Form)
        self.psinus.setGeometry(QtCore.QRect(300, 70, 75, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.psinus.setFont(font)
        self.psinus.setObjectName("psinus")
        self.pcarp = QtWidgets.QPushButton(Form)
        self.pcarp.setGeometry(QtCore.QRect(20, 150, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pcarp.setFont(font)
        self.pcarp.setObjectName("pcarp")
        self.psil = QtWidgets.QPushButton(Form)
        self.psil.setGeometry(QtCore.QRect(250, 320, 75, 23))
        self.psil.setObjectName("psil")
        self.p7 = QtWidgets.QPushButton(Form)
        self.p7.setGeometry(QtCore.QRect(120, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p7.setFont(font)
        self.p7.setObjectName("p7")
        self.pkotanjant = QtWidgets.QPushButton(Form)
        self.pkotanjant.setGeometry(QtCore.QRect(300, 190, 75, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pkotanjant.setFont(font)
        self.pkotanjant.setObjectName("pkotanjant")
        self.p3 = QtWidgets.QPushButton(Form)
        self.p3.setGeometry(QtCore.QRect(240, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p3.setFont(font)
        self.p3.setObjectName("p3")
        self.ptanjant = QtWidgets.QPushButton(Form)
        self.ptanjant.setGeometry(QtCore.QRect(300, 150, 75, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ptanjant.setFont(font)
        self.ptanjant.setObjectName("ptanjant")
        self.p8 = QtWidgets.QPushButton(Form)
        self.p8.setGeometry(QtCore.QRect(180, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p8.setFont(font)
        self.p8.setObjectName("p8")
        self.p0 = QtWidgets.QPushButton(Form)
        self.p0.setGeometry(QtCore.QRect(180, 220, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p0.setFont(font)
        self.p0.setObjectName("p0")
        self.pesittir = QtWidgets.QPushButton(Form)
        self.pesittir.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.pesittir.setObjectName("pesittir")
        self.p1 = QtWidgets.QPushButton(Form)
        self.p1.setGeometry(QtCore.QRect(120, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.setObjectName("p1")
        self.p6 = QtWidgets.QPushButton(Form)
        self.p6.setGeometry(QtCore.QRect(240, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p6.setFont(font)
        self.p6.setObjectName("p6")
        self.pkosinus = QtWidgets.QPushButton(Form)
        self.pkosinus.setGeometry(QtCore.QRect(300, 110, 75, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pkosinus.setFont(font)
        self.pkosinus.setObjectName("pkosinus")
        self.ptopla = QtWidgets.QPushButton(Form)
        self.ptopla.setGeometry(QtCore.QRect(20, 70, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ptopla.setFont(font)
        self.ptopla.setObjectName("ptopla")
        self.p2 = QtWidgets.QPushButton(Form)
        self.p2.setGeometry(QtCore.QRect(180, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p2.setFont(font)
        self.p2.setObjectName("p2")
        self.pcikar = QtWidgets.QPushButton(Form)
        self.pcikar.setGeometry(QtCore.QRect(20, 110, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pcikar.setFont(font)
        self.pcikar.setObjectName("pcikar")
        self.lineekran = QtWidgets.QLineEdit(Form)
        self.lineekran.setGeometry(QtCore.QRect(42, 20, 301, 31))
        font = QtGui.QFont()
        self.label=QtWidgets.QLabel(Form)
        self.p5 = QtWidgets.QPushButton(Form)
        self.p5.setGeometry(QtCore.QRect(180, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p5.setFont(font)
        self.p5.setObjectName("p5")
        self.p9 = QtWidgets.QPushButton(Form)
        self.p9.setGeometry(QtCore.QRect(240, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p9.setFont(font)
        self.p9.setObjectName("p9")
        self.pbol = QtWidgets.QPushButton(Form)
        self.pbol.setGeometry(QtCore.QRect(20, 190, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbol.setFont(font)
        self.pbol.setObjectName("pbol")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 360, 121, 20))
        self.label.setObjectName("label")
        self.pkotciz = QtWidgets.QPushButton(Form)
        self.pkotciz.setGeometry(QtCore.QRect(280, 270, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pkotciz.setFont(font)
        self.pkotciz.setObjectName("pkotciz")
        self.psinusciz = QtWidgets.QPushButton(Form)
        self.psinusciz.setGeometry(QtCore.QRect(10, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.psinusciz.setFont(font)
        self.psinusciz.setObjectName("psinusciz")
        self.pcosciz = QtWidgets.QPushButton(Form)
        self.pcosciz.setGeometry(QtCore.QRect(100, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pcosciz.setFont(font)
        self.pcosciz.setObjectName("pcosciz")
        self.ptanciz = QtWidgets.QPushButton(Form)
        self.ptanciz.setGeometry(QtCore.QRect(190, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ptanciz.setFont(font)
        self.ptanciz.setObjectName("ptanciz")

        self.retranslateUi(Form)
        self.p1.pressed.connect(lambda i="1": self.ekle(i))
        self.p2.pressed.connect(lambda i="2": self.ekle(i))
        self.p3.pressed.connect(lambda i="3": self.ekle(i))
        self.p4.pressed.connect(lambda i="4": self.ekle(i))
        self.p5.pressed.connect(lambda i="5": self.ekle(i))
        self.p6.pressed.connect(lambda i="6": self.ekle(i))
        self.p7.pressed.connect(lambda i="7": self.ekle(i))
        self.p8.pressed.connect(lambda i="8": self.ekle(i))
        self.p9.pressed.connect(lambda i="9": self.ekle(i))
        self.p0.pressed.connect(lambda i="0": self.ekle(i))
        self.pkotanjant.pressed.connect(self.kot)
        self.ptanjant.pressed.connect(self.tan)
        self.pkosinus.pressed.connect(self.cos)
        self.psinus.pressed.connect(self.sin)
        self.pcikar.pressed.connect(self.cikarma)
        self.pcarp.pressed.connect(self.carpma)
        self.pbol.pressed.connect(self.bolme)
        self.pcikis.clicked.connect(Form.close)
        self.pesittir.pressed.connect(self.esittir)
        self.psil.pressed.connect(self.temizle)
        self.ptopla.pressed.connect(self.topla)
        self.pcosciz.pressed.connect(self.cosgrafik)
        self.pkotciz.released.connect(self.kotgrafik)
        self.psinusciz.pressed.connect(self.singrafik)
        self.ptanciz.pressed.connect(self.tangrafik)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.p4.setText(_translate("Form", "4"))
        self.pcikis.setText(_translate("Form", "Kapat"))
        self.psinus.setText(_translate("Form", "Sinus"))
        self.pcarp.setText(_translate("Form", "Carp"))
        self.psil.setText(_translate("Form", "Sil"))
        self.p7.setText(_translate("Form", "7"))
        self.pkotanjant.setText(_translate("Form", "Kotanjant"))
        self.p3.setText(_translate("Form", "3"))
        self.ptanjant.setText(_translate("Form", "Tanjant"))
        self.p8.setText(_translate("Form", "8"))
        self.p0.setText(_translate("Form", "0"))
        self.pesittir.setText(_translate("Form", "Sonuc"))
        self.p1.setText(_translate("Form", "1"))
        self.p6.setText(_translate("Form", "6"))
        self.pkosinus.setText(_translate("Form", "kosinus"))
        self.ptopla.setText(_translate("Form", "Topla"))
        self.p2.setText(_translate("Form", "2"))
        self.pcikar.setText(_translate("Form", "Cikar"))
        self.p5.setText(_translate("Form", "5"))
        self.p9.setText(_translate("Form", "9"))
        self.pbol.setText(_translate("Form", "Bol"))
        self.label.setText(_translate("Form", "Designed By Turan Guclu"))
        self.pkotciz.setText(_translate("Form", "Kotanjant Ciz"))
        self.psinusciz.setText(_translate("Form", "Sinus Ciz"))
        self.pcosciz.setText(_translate("Form", "Kosinus Ciz"))
        self.ptanciz.setText(_translate("Form", "Tanjant Ciz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

